export enum EConversationEndStatus {
  ISSUE_RESOLVED = "ISSUE_RESOLVED",
  SPAM = "SPAM",
  NO_AGENT_AVAILABLE = "NO_AGENT_AVAILABLE",
  STOP_SUPPORT_REQUEST = "STOP_SUPPORT_REQUEST",
  CUSTOMER_RESPONSE_TIMEOUT = "CUSTOMER_RESPONSE_TIMEOUT",
  NO_VISITOR_MESSAGE = "NO_VISITOR_MESSAGE",
  QUEUE_TIMEOUT = "QUEUE_TIMEOUT",
  ADMIN_FORCE_CLOSED = "ADMIN_FORCE_CLOSED",
  /** @deprecated Giữ lại cho dữ liệu cũ. Sử dụng status cụ thể ở trên. */
  CLOSED_AUTOMATICALLY_BY_SYSTEM = "CLOSED_AUTOMATICALLY_BY_SYSTEM",
}
