export enum EConversationEndStatus {
    ISSUE_RESOLVED = "ISSUE_RESOLVED",
    SPAM = "SPAM",
    NO_AGENT_AVAILABLE = "NO_AGENT_AVAILABLE",
    STOP_SUPPORT_REQUEST = "STOP_SUPPORT_REQUEST",
    CLOSED_AUTOMATICALLY_BY_SYSTEM = "CLOSED_AUTOMATICALLY_BY_SYSTEM",
}
